services:
    prostar_web:
        build: .
        ports:
            - "5000:5000"
        networks:
            - npm_network
        env_file:
            - .flaskenv
        volumes:
            - ./data:/data
        restart: unless-stopped

networks:
    npm_network:
        external: true
